HyeJin/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
      
    
    # Example : /blog/archive/today/
    path('tag/',views.TagCloudTV.as_view(),name='tag_cloud'),
    
    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(),name='tagged_object_list'),
    
    path('search/',views.SearchFV.as_view(),name='search'),
    
    path('add/', views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

HyeJin/mysite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mysite import views


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register/',views.UserCreateView.as_view(),name="register"),
    path('accounts/register/done',views.UserCreateDoneTV.as_view(),name='register_done'),
    
    path('',views.HomeView.as_view(), name='home'),
    
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

HyeJin/photo/urls.py
from django.urls import path
from photo import views

app_name='photo'
urlpatterns = [
    # Example : /photo/
    path('',views.AlbumLV.as_view(),name="index"),
    
    # Example : /photo/album/, same as /photo/
    path('album',views.AlbumLV.as_view(),name="album_list"),
    
    # Example : /photo/album/99
    path('album/<int:pk>/',views.AlbumDV.as_view(),name="album_detail"),
    
    # Example : /photo/photo/99
    path('photo/<int:pk>/',views.PhotoDV.as_view(),name="photo_detail"),
    
    path('album/add/',views.AlbumCV.as_view(),name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(),name='album_change'),
    path('album/<int:pk>/update/',views.AlbumUV.as_view(),name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(),name='album_delete'),
    
    path('photo/add/',views.PhotoCV.as_view(),name='photo_add'),
    path('photo/change/',views.PhotoChangeLV.as_view(),name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(),name='photo_delete'),

]

HyeJin/photo/models.py
from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField
# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User',on_delete = models.CASCADE,verbose_name='OWNER',blank=True, null=True)
    
    class Meta:
        ordering=('id',)
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail',args=(self.id,))
    
class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=40)
    url = models.URLField('URL', unique=True, blank=True, null=True)
    description = models.TextField('Photo Description',blank=True)
    image = ThumbnailImageField(upload_to = 'photo/%Y/%m')
    upload_dt = models.DateTimeField('upload Date', auto_now_add=True)
    owner = models.ForeignKey('auth.User',on_delete = models.CASCADE,verbose_name='OWNER',blank=True, null=True)
    
    class Meta:
        ordering=('title',)
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail',args=(self.id,))

HyeJin/photo/forms.py
from django.forms import inlineformset_factory
from .models import *

PhotoInlineFormSet=inlineformset_factory(Album,
                                         Photo,
                                         fields = ['image', 'title','url', 'description'],
                                         extra = 2
                                         )

HyeJin/photo/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import Album, Photo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .models import Album, Photo
from .forms import PhotoInlineFormSet
from mysite.views import OwnerOnlyMixin

# Create your views here.
class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album
    
class PhotoDV(DetailView):
    model = Photo
        
class AlbumCV(LoginRequiredMixin, CreateView):
    model=Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid() :
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
        
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'
    
    def get_queryset(self):
        return Album.objects.filter(owner = self.request.user)
    
class AlbumUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else :
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else :
            return self.render_to_response(self.get_context_data(form=form))
        
class AlbumDelV(OwnerOnlyMixin,DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')
    
class PhotoCV(LoginRequiredMixin,CreateView):
    model = Photo
    fields = ('album','title','url','image','description')
    success_url = reverse_lazy('photo:index')
    
    def form_valid(self,form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'
    
    def get_queryset(self):
        return Photo.objects.filter(owner = self.request.user)
    
class PhotoUV(LoginRequiredMixin,UpdateView):
    model = Photo
    fields = ('album','title','url','image','description')
    success_url = reverse_lazy('photo:index')

class PhotoDelV(LoginRequiredMixin,DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

HyeJin/photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <h1>Album Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
    <br>
    
    <form method="post">{% csrf_token %}
        <p>앨범 "{{ object }}"을/를 삭제하면, 그 안의 모든 사진들도 삭제됩니다. 동의하십니까?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/album_detail.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Album Detail Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
<style>
    .photo-card {
        margin-bottom: 30px;
        box-shadow: 0px 2px 10px rgb(0 0 0 / 15%);
        transition: 0.4s ease;
        height: 435.66px;
    }
    .photo-card:hover {
        transform: translateY(-10px) scale(1.02);
        box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.15) !important;
    }
    .card {
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 1px solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }
    .card-body {
        text-align: justify;
        word-break: break-all;
    }
    .ellipsis {
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 4;
        -webkit-box-orient: vertical;
    }
</style>
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <h3>Detail</h3>
    <div class="row">
        <div class="mb-5">
            <div class="d-block mt-3 mb-5">
                &nbsp&nbsp&nbsp&nbsp&nbsp<a href="{% url 'photo:index' %}" class="mb-3 btn btn-outline-dark"> {{ object }} </a>
                <p class="ml-5">{{ object.description }}</p>
                <div class="ml-5 row">   
                {% for photo in object.photo_set.all|slice:":6" %}
                    <div class="col-md-6 col-lg-4">
                        <div class="card photo-card">
                            <a href="{{ photo.get_absolute_url }}">
                                <img src="{{ photo.image.thumb_url }}" alt="{{ photo }}" width="100%">
                            </a>
                            <div class="card-body">
                                <h6>{{ photo }}</h6>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}
{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
<h1>Album-Photo Create/Update - {{user}}</h1>
<p class="font-italic">PhotoInlineFormSet을 이용한 추가, 수정 폼 화면입니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
    {{ formerrors }}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
        {% endif %}
        {% csrf_token %}

        <h4>앨범을 추가하거나 수정하세요</h4>

        <fieldset class="card pt-3">

            <div class="form-group row">
                {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.description|add_class:"form-control" }}
                </div>
            </div>

        </fieldset>

        <br>

        <h4>사진을 추가하거나 수정하세요.</h4>

        <fieldset class="card pt-3">

            {{ formset.management_form }}
            {% for form in formset %}
            {{ form.id }}
            {# form.album #}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <hr>
            {% endfor %}

        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/album_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Album List Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>

<div id="main-content" class="container">
    <h3>Imformations</h3>
    <div class="row">
        <div class="mb-5">
            {% for object in object_list %}
                <div class="d-block mt-3 mb-5">
                    &nbsp&nbsp&nbsp&nbsp&nbsp<a href="{{ object.get_absolute_url }}" class="mb-3 btn btn-outline-dark"> {{ object }} </a>
                    <p class="ml-5">{{ object.description }}</p>
                    <div class="ml-5 row">
                    {% for photo in object.photo_set.all|slice:":4" %}
                        <div class="col-3">
                        <a href="{{ photo.get_absolute_url }}" class="btn border">
                            <img src="{{ photo.image.thumb_url }}" alt="{{ photo }}" width="100%">
                        </a>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}
{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <h1>Photo Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-info">
                <th>Album</th>
                <th>Title</th>
                <th>Url</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.album }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}

<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <h1>Photo Delete</h1>
    <br>
    
    <form method="post"> {% csrf_token %}
        <p>이미지 "{{ object }}"을/를 진심으로 삭제하는건가요?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}

{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
    <span style="background: #F9F7F6; border-left: 0.5em solid #3A4CA8; padding: 0.5em;">Detail</span><br>
    
    <p class='text'><h3 class="display-5 fw-bolder">{{ object }}</h3> Date : {{ object.upload_dt|date:"Y-m-d"}}</p>
    <div class="row gx-4 gx-lg-5 align-items-center">
        <div class="col-md-6">
            <img class="card-img-top mb-5 mb-md-0" src="{{ object.image.url }}" alt="{{ photo }}">
        </div>
        <div class="col-md-6">
            <a href="{{ object.url }}"> 본문 URL </a><br>
            <p class="lead"><h6>Content :</h6> {{ object.description|linebreaksbr }}</p>
        </div>
        
    </div>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}
{% endblock %}
<!-- 스크립트 블록 End -->

HyeJin/photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div style="padding:10px;">&nbsp</div>
<div id="main-content" class="container">
<h1>Photo Create/Update - {{ user }}</h1>
<p class="font-italic">사진 업로드 또는 수정을 진행할 수 있습니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" class="card pt-3">
{% else %}
    <form method="post" class="card pt-3">
{% endif %}
        {% csrf_token %}

        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">
                    Add Album</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->