HyeJin/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
      
    
    # Example : /blog/archive/today/
    path('tag/',views.TagCloudTV.as_view(),name='tag_cloud'),
    
    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(),name='tagged_object_list'),
    
    path('search/',views.SearchFV.as_view(),name='search'),
    
    path('add/', views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

HyeJin/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    
    path('add/', views.BookmarkCreateView.as_view(),name='add'),
    path('change/',views.BookmarkChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.BookmarkUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.BookmarkDeleteView.as_view(),name='delete'),
]

HyeJin/mysite/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mysite import views


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register/',views.UserCreateView.as_view(),name="register"),
    path('accounts/register/done',views.UserCreateDoneTV.as_view(),name='register_done'),
    
    path('',views.HomeView.as_view(), name='home'),
    
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

HyeJin/photo/urls.py
from django.urls import path
from photo import views

app_name='photo'
urlpatterns = [
    # Example : /photo/
    path('',views.AlbumLV.as_view(),name="index"),
    
    # Example : /photo/album/, same as /photo/
    path('album',views.AlbumLV.as_view(),name="album_list"),
    
    # Example : /photo/album/99
    path('album/<int:pk>/',views.AlbumDV.as_view(),name="album_detail"),
    
    # Example : /photo/photo/99
    path('photo/<int:pk>/',views.PhotoDV.as_view(),name="photo_detail"),
    
    path('album/add/',views.AlbumCV.as_view(),name='album_add'),
    path('album/change/',views.AlbumChangeLV.as_view(),name='album_change'),
    path('album/<int:pk>/update/',views.AlbumUV.as_view(),name='album_update'),
    path('album/<int:pk>/delete/',views.AlbumDelV.as_view(),name='album_delete'),
    
    path('photo/add/',views.PhotoCV.as_view(),name='photo_add'),
    path('photo/change/',views.PhotoChangeLV.as_view(),name='photo_change'),
    path('photo/<int:pk>/update/',views.PhotoUV.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(),name='photo_delete'),

]

HyeJin/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- 제목 블록 Start (기본값 My Blog Page) -->
    <title>    
        {% block title %}
            My Blog Page
        {% endblock %}
    </title>
    <!-- 제목 블록 End -->

    <!-- Bootstrap CSS only -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- font change [pretendard] -->
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard.css" />
    
    <!-- 공통 스타일 적용 Start -->
    <style>
        * {
            font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif;
        }
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        #main-wrapper{
            margin: 10px 0;
            height: auto;
            min-height: 100%;
            padding-bottom: 266px;
        }
        footer {
            height: 266px;
            position: relative;
            transform : translateY(-100%);
            width: 100%;
            padding: 60px 0;
            background: #252629;
        }
        #contact_info  * {
            color: #96989c;
            font-size: 14px;
        }
    
        footer .footer_logo {
            padding-bottom: 24px;
            color: #fff;
            font-weight: 600;
        }
        .logo{
            opacity:0.85;
        }
    </style>
    <!-- 공통 스타일 적용 End -->

    <!-- 스타일 블록 Start -->
    {% block extra-style %}
    {% endblock %}
    <!-- 스타일 블록 End -->
</head>



<body>
    <!-- 네비게이션 바 Start -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-white">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <a class="navbar-brand" href="https://corp.afreecatv.com/">
                <style>
                    img {margin : auto;}
                </style>
                <div class='logo'>
                <img src="/static/img/아프리카TV 로고.png" style="background:none" alt="AfreecaTV" height="20" width="115" data-atf="1" data-frt="0"></a></div>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-muted" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-muted" href="{% url 'bookmark:index' %}">Employment</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-muted" href="{% url 'blog:index' %}">News</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-muted" href="{% url 'photo:index' %}">Imformation</a>
                </li>
                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:add' %}">Employment</a>
                        <a class="dropdown-item" href="{% url 'blog:add' %}">News</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">Category</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Imformation</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:change' %}">Employment</a>
                        <a class="dropdown-item" href="{% url 'blog:change' %}">News</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_change' %}">Category</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Imformation</a>
                    </div>
                </li>
            </ul>
            <!-- 
            <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->

            <!--  -->
            <ul class="navbar-nav mx-5">
                <li class="nav-item dropdown mx-1 btn btn-white">
                    {% if user.is_active %} <!-- 로그인된 상태라면 -->
                    <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    </div>
                    {% else %} <!-- 로그인된 상태가 아니라면 -->
                    <a class="nav-link dropdown-toggle text-muted" href="#" data-toggle="dropdown">
                        로그인 / 회원가입
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    </div>
                    {% endif %}
                </li>
            </ul>
            <!--  -->
        </div>
    </nav>
    <!-- 네비게이션 바 End -->
    

    <div id="main-wrapper">
        <!-- 콘텐츠 블록 Start -->
        {% block content %}
        <div id="main-content" class="container"></div>
        {% endblock %}
        <!-- 콘텐츠 블록 End -->
    </div>

    <!-- 푸터 Start -->
    <footer>
        <div class="container">
            <div class="footer_logo">About AfreecaTV</div>
            <div id="contact_info">
                <p>
                    <a class="text-decoration-none" href="tel:+821071938445"><i class="fa-solid fa-phone"></i>&emsp;010-3898-4740</a>
                    <br>
                    <a class="text-decoration-none" href="mailto:484342@gmail.com"><i class="fa-solid fa-envelope"></i>&emsp;data.hyejin@gmail.com</a>
                    <br>
                    <a class="text-decoration-none" href="https://www.instagram.com/_zzynee" target="_blank"><i class="fa-brands fa-square-instagram"></i>&emsp;@_zzynee</a>
                </p>
            </div>
            <p style="color:#646873">Copyright © <b>Jeong Hye Jin</b> All rights reserved.</p>
        </div>
    </footer>
    <!-- 푸터 End -->
</body>

<script src="https://kit.fontawesome.com/600ceba5b1.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->
</html>

HyeJin/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
My Blog Main Page
{% endblock %}

{% block extra-style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<style>
    {% comment %} .home-image {
        background-image: url("{% static 'img/로고.jpg' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    } {% endcomment %}

    #font {
        position: relative;
        top: -70px;
    }
    .myname {
        position: relative;
        top: -60px;
    }
    .powered {
        position: relative;
        top: 90%;
        color: #cc0;
        margin-right: 3%;
        text-align: right;
        font-style: italic;
    }
    
    .pic{
        opacity:0.8;
    }
    .bg-image-full {
        line-height: 100px;
        background-image: url('{% static 'img/캐릭터.jpg' %}');
        background-repeat: no-repeat;   
        background-size: cover;
    }
    h1 {
        vertical-align: top;
        text-align: center;
    }

    .service-icon {
        position: relative;
        margin: -50px 0 25px 0;
        width: 100px;
        height: 100px;
        display: flex;
        align-items: center;
        justify-content: center;
        color: var(--primary);
        background: #FFFFFF;
        border-radius: 100px;
        box-shadow: 0 0 45px rgba(0, 0, 0, .08);
        transition: .5s;
    }
    .service-item:hover .service-icon {
        color: #FFFFFF;
        background: var(--primary);
    }

    .service-item {
        box-shadow: 0 0 45px rgba(0, 0, 0, .08);
    }

    .img-fluid {
        height: 435.66px;
    }
</style>
{% endblock %}


{% block content %}
    <div class='pic'>
        <header class="py-5 bg-image-full">
            <div class="container py-5">
                <div class="text-center my-5" id='font'>
                    <h1 class="text-white fs-3 fw-bolder animate__animated animate__slideInDown" style="text-shadow:0px 1px 1px #000;">Anybody can Freely Broadcast TV</h1>
                    <p class="text-blue-50 mb-0 myname" >&nbsp</p>
                </div>
            </div>

        </header>
    </div>

    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center mx-auto mb-5 wow animate__animated animate__fadeInUp" data-wow-delay="0.1s" style="max-width: 600px; visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                <h6 class="text-primary">AfreecaTV</h6>
                <h2 class="mb-4">세상의 모든 꿈을 생방송하다</h2>
            </div>
            <div class="row g-4">
                <div class="col-md-6 col-lg-4 wow animate__animated animate__fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                    <div class="service-item rounded overflow-hidden">
                        <a href="https://www.afreecatv.com/">
                            <div style="width:350px; height:400px; overflow:hidden">
                            <img class="img-fluid" src="{% static 'img/캐릭터1.jpg' %}" alt="">
                            </div>
                        </a>
                        <div class="position-relative p-4 pt-0">
                            <div class="service-icon">
                                <i class="fa-solid fa-star fa-3x"></i>
                            </div>
                            <h4 class="mb-3">아프리카TV 방송국</h4>
                            <p>언제 어디서나, 누구나 쉽게 실시간 방송을 할 수 있는 유무선 통합 SNS미디어</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 wow animate__animated animate__fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
                    <div class="service-item rounded overflow-hidden">
                        <a href="https://library.kaist.ac.kr/search/detail/view.do?bibCtrlNo=719423&flag=dissertation">
                            <div style="width:350px; height:400px; overflow:hidden">
                            <img class="img-fluid" src="{% static 'img/대표님.jpg' %}" alt="">
                            </div>
                        </a>
                        <div class="position-relative p-4 pt-0">
                            <div class="service-icon">
                                <i class="fa-regular fa-file fa-3x"></i>
                            </div>
                            <h4 class="mb-3">정찬용 대표님 논문</h4>
                            <p>라이브 스트리밍 서비스의 상호작용성이 후원아이템 구매에 미치는 영향에 대한 논문</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 wow animate__animated animate__fadeInUp" data-wow-delay="0.5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
                    <div class="service-item rounded overflow-hidden">
                        <a href="https://bj.afreecatv.com/afreecatvhr/vods">
                            <div style="width:350px; height:400px; overflow:hidden">
                                <img class="img-fluid" src="{% static 'img/채용.jpg' %}" alt="">
                            </div>
                        </a>
                        <div class="position-relative p-4 pt-0">
                            <div class="service-icon">
                                <i class="fa-solid fa-cloud fa-3x"></i>
                            </div>
                            <h4 class="mb-3">아프리카TV 채용 VOD</h4>
                            <p>신입 공개 채용 설명회, 직무 설명회, 현직자가 알려주는 아프리카TV의 모든것</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    
    <div id="main-content" class="container">
        <hr style="margin: 10px 0">

        <div class="row text-center mt-5">
            <div class="col-sm-6">
                <h4>사람인</h4>
                <p>이력서 / 자기소개서 / 포트폴리오</p>
                <a class="small fw-medium" href="https://www.saramin.co.kr/zf_user/?NaPm=ct%3Dl8meln12%7Cci%3Dcheckout%7Ctr%3Dds%7Ctrx%3D%7Chk%3Dbc8045a92c21b9f8078f36fcc1d8638e836f891d">Read More<i class="fa fa-arrow-right ms-2"></i></a><br><br>
            </div>
            <div class="col-sm-6">
                <h4>Blog</h4>
                <p>취업사관학교 / 특강 후기 / 프로젝트</p>
                <a class="small fw-medium" href="https://blog.naver.com/data_hyejin">Read More<i class="fa fa-arrow-right ms-2"></i></a><br><br><br>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra-script %}
{% endblock %}

HyeJin/templates/template.html
{% extends 'base.html' %}

<!--제목 블록 start (기본값 My Blog Page)-->
{% block title %}
{% endblock %}
<!--제목 블록 End-->

<!--스타일 블록 Start-->
{% block extra-style %}
{% endblock %}
<!--스타일 블록 End-->

<!--콘텐츠 블록 Start-->
{% block content %}
{% endblock %}
<!--콘텐츠 블록 End-->

<!--스크립트 블록 Start-->
{% block extra-script %}
{% endblock %}
<!--스크립트 블록 End-->